### ISSUE TITLE
Cannot connect one of my computer 

### ISSUE THREAD

**Issue by epyon1873** [BHznJNs/InputShare#13]
Cannot via USB with this error prompted

Traceback (most recent call last):
  File "main.py", line 58, in <module>
  File "server\__init__.py", line 15, in deploy_scrcpy_server
  File "adbutils\_device.py", line 246, in forward
  File "adbutils\_device.py", line 97, in open_transport
  File "adbutils\_adb.py", line 134, in check_okay
adbutils.errors.AdbError: cannot bind listener: cannot bind to 127.0.0.1:1234: An attempt was made to access a socket in a way forbidden by its access permissions. (10013)

using Scrcpy is no problem.

**Comment by BHznJNs** [comment]
I assume that this error is caused by port conflict which will be improved the next minor version.

**Comment by epyon1873** [comment]
The issue still exist on 0.7.2 
FYI.

**Comment by BHznJNs** [comment]
Thank your for feedback, recently i have no enough time to resolve it, it may be resolved next month.

**Comment by BHznJNs** [comment]
Maybe you could retry with the latest release
https://github.com/BHznJNs/InputShare/releases/tag/0.7.5
