### ISSUE TITLE
打开边缘切换会报错

### ISSUE THREAD

**Issue by 302991530** [BHznJNs/InputShare#18]
Traceback (most recent call last):
  File "main.py", line 68, in <module>
  File "server\__init__.py", line 34, in deploy_reporter_server
  File "adbutils\_device.py", line 246, in forward
  File "adbutils\_device.py", line 97, in open_transport
  File "adbutils\_adb.py", line 134, in check_okay
adbutils.errors.AdbError: cannot bind listener: cannot bind to 127.0.0.1:61625: 以一种访问权限不允许的方式做了一个访问套接字的尝试。 (10013)

电脑win10.手机是安卓15，通过wifi连接

**Comment by BHznJNs** [comment]
请问使用最新的版本还会出现这个问题吗？

**Comment by 302991530** [comment]
> 请问使用最新的版本还会出现这个问题吗？

软件启动后设置里开启边缘切换，再点开启键鼠共享，就可以使用边缘切换，
但是设置好重启软件后，就打不开了，需要在配置里面设置为false后方可启动

另外手机端没有自动安装app，我记得之前是有的

还有一个时不时弹出来的报错
![Image](https://github.com/user-attachments/assets/91fae59e-8692-4063-95da-3293a4c073c1)
Traceback (most recent call last):
  File "adbutils\_adb.py", line 88, in read
  File "adbutils\_adb.py", line 96, in _read_fully
TimeoutError: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "server\reporter_receiver.py", line 29, in install_server
  File "decorator.py", line 235, in fun
  File "retry\api.py", line 73, in retry_decorator
  File "retry\api.py", line 33, in __retry_internal
  File "adbutils\_device.py", line 904, in install
  File "adbutils\_device.py", line 959, in install_remote
  File "adbutils\_device.py", line 208, in shell
  File "adbutils\_adb.py", line 125, in read_until_close
  File "adbutils\_adb.py", line 90, in read
adbutils.errors.AdbTimeout: adb read timeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 68, in <module>
  File "server\__init__.py", line 47, in deploy_reporter_server
  File "server\reporter_receiver.py", line 30, in install_server
TypeError: catching classes that do not inherit from BaseException is not allowed

**Comment by 1010655510** [comment]
Traceback (most recent call last):
  File "server\reporter_receiver.py", line 29, in install_server
  File "decorator.py", line 235, in fun
  File "retry\api.py", line 73, in retry_decorator
  File "retry\api.py", line 33, in __retry_internal
  File "adbutils\_device.py", line 904, in install
  File "adbutils\_device.py", line 961, in install_remote
adbutils.errors.AdbInstallError: Failure [INSTALL_FAILED_USER_RESTRICTED: Install canceled by user]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 75, in <module>
  File "server\__init__.py", line 38, in deploy_reporter_server
  File "server\reporter_receiver.py", line 30, in install_server
TypeError: catching classes that do not inherit from BaseException is not allowed
Win10-Android13

**Comment by FRANK641** [comment]
遇到了同样的问题，作者大大啥事后能修啊，
版本：0.8.1a Update
<img width="503" height="734" alt="Image" src="https://github.com/user-attachments/assets/2271861f-69e7-4b36-9bda-3161abaea198" />
